apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  labels:
    app: frontend-deployment
spec:
  type: NodePort
  selector:
    run: frontend-deployment
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP

